import * as runtime from "$lib/paraglide/runtime";
import { createI18n } from "@inlang/paraglide-js-adapter-sveltekit";

// Type definition for the Paraglide runtime generated by inlang (mapped to the adapter's expectations)
type ParaglideRuntime = Parameters<typeof createI18n>[0];

// Define what we know exists in the generated runtime.js
interface GeneratedRuntime {
  baseLocale: string;
  locales: readonly string[];
  getLocale(): string;
  setLocale(lang: string): void;
}

const gen = runtime as unknown as GeneratedRuntime;

const paraglideRuntime: ParaglideRuntime = {
  ...runtime,
  sourceLanguageTag: gen.baseLocale,
  availableLanguageTags: gen.locales,
  isAvailableLanguageTag(lang: string): lang is string {
    return gen.locales.includes(lang);
  },
  languageTag() {
    return gen.getLocale();
  },
  setLanguageTag(lang: string) {
    return gen.setLocale(lang);
  },
  // Provide a dummy for the required property if it's missing in the generated runtime
  onSetLanguageTag: () => {},
} as unknown as ParaglideRuntime;

export const i18n = createI18n(paraglideRuntime);

// Map Paraglide names for consistent usage in the app
export const languageTag = gen.getLocale;
export const availableLanguageTags = gen.locales;

export { i18n as adapter };
